/**
 * Selbstsignierte Test-Zertifikate (EC P-256, 100 Jahre gültig) für die
 * Loopback-Pinning-Tests — simulieren Proton Bridge bzw. einen Fremdprozess.
 */
export const CERT_A = `-----BEGIN CERTIFICATE-----
MIIBxzCCAW2gAwIBAgIUJnSdmtXe5OgaYNUmxrodwTSTEq8wCgYIKoZIzj0EAwIw
KjEUMBIGA1UECgwLTm9jdHVhIFRlc3QxEjAQBgNVBAMMCTEyNy4wLjAuMTAgFw0y
NjEwMDYwNTQ5MjBaGA8yMTI2MDkxMjA1NDkyMFowKjEUMBIGA1UECgwLTm9jdHVh
IFRlc3QxEjAQBgNVBAMMCTEyNy4wLjAuMTBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABNaxoOsZkkw79fQOy35uTgDAiJuXSm2VubO/oMmGeBPc1hSDIOEMzxTPmOow
p4/ozofTyI/3lgViLiMLcRsxh3OjbzBtMB0GA1UdDgQWBBRYkpHjQG8Vb8BzPXG4
pY7cs1WunDAfBgNVHSMEGDAWgBRYkpHjQG8Vb8BzPXG4pY7cs1WunDAPBgNVHRMB
Af8EBTADAQH/MBoGA1UdEQQTMBGHBH8AAAGCCWxvY2FsaG9zdDAKBggqhkjOPQQD
AgNIADBFAiEAru0RPgn1RoINRxUO1MZbSC8zSEB1kPfNWdb17J3HMSwCIELNRoNS
82hnGkk5fC26KFuYOxELs8GArKBYOwvyT99s
-----END CERTIFICATE-----
`
export const KEY_A = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgEKNFxti2+6vGJHmo
skWHjFweYx8iI81KgjkngAn9EvKhRANCAATWsaDrGZJMO/X0Dst+bk4AwIibl0pt
lbmzv6DJhngT3NYUgyDhDM8Uz5jqMKeP6M6H08iP95YFYi4jC3EbMYdz
-----END PRIVATE KEY-----
`
export const CERT_B = `-----BEGIN CERTIFICATE-----
MIIBxzCCAW2gAwIBAgIUMypPRQm6FJjXjYULxR99IYI4FLwwCgYIKoZIzj0EAwIw
KjEUMBIGA1UECgwLTm9jdHVhIFRlc3QxEjAQBgNVBAMMCTEyNy4wLjAuMTAgFw0y
NjEwMDYwNTQ5MjBaGA8yMTI2MDkxMjA1NDkyMFowKjEUMBIGA1UECgwLTm9jdHVh
IFRlc3QxEjAQBgNVBAMMCTEyNy4wLjAuMTBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABL/kms/1AuXt0vudlRCaB0lW7IbDZPSi0JW8HZrM36oe/6WnBT2pQ6a9j5+V
tU6O8Fb6o77zNPeFeInQlluHBlqjbzBtMB0GA1UdDgQWBBTypU4lyGgJrlWc9wSL
jed0RjbBpzAfBgNVHSMEGDAWgBTypU4lyGgJrlWc9wSLjed0RjbBpzAPBgNVHRMB
Af8EBTADAQH/MBoGA1UdEQQTMBGHBH8AAAGCCWxvY2FsaG9zdDAKBggqhkjOPQQD
AgNIADBFAiEA06Lb8HqS5iHGswKthyny4HD8r8BZ/aXK6kiPTxA1Vi4CICanuvx8
0v7lA22ItsJvYDDEjswuOyoH5ibNaNPT/ctH
-----END CERTIFICATE-----
`
export const KEY_B = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgx7V+ggFYxJaOn7Jq
us75U8pnwuU9618OjwkafG88ikqhRANCAAS/5JrP9QLl7dL7nZUQmgdJVuyGw2T0
otCVvB2azN+qHv+lpwU9qUOmvY+flbVOjvBW+qO+8zT3hXiJ0JZbhwZa
-----END PRIVATE KEY-----
`
